### ISSUE TITLE
add support for PDF files as input

### ISSUE THREAD

**Issue by satyanash** [rahul-gaidhane/project_mag#10]
As you may have noted, some of the other issues are available in PDF files. We will also have to add support to split the PDF into individual images instead of the TIFFs.

**Comment by rahul-gaidhane** [comment]
support for pdf is provided

**Comment by satyanash** [comment]
The images that are extracted from the PDF are not of the highest possible quality. Our code seems to be using the defaults which scale the images down to a size where the text is not readable. We need to extract the images in the highest possible quality.

For example, the first image in the first file (April1991-Aank1.pdf), is extracted at a size of `612x623`. This makes it unreadable in the browser.

**Comment by satyanash** [comment]
Check this stackoverflow post for ideas on how to better extract images from a PDF: 
https://stackoverflow.com/questions/6605006/convert-pdf-to-image-with-high-resolution

Try understanding what it does and why those specific options work.

**Comment by satyanash** [comment]
Update on this.

**Comment by rahul-gaidhane** [comment]
I used the sharpen option for an individual image extracted here.it improved but text was still not readable

**Comment by satyanash** [comment]
Try using:
```
convert -verbose -density 150 -trim April1991-Aank1.pdf -quality 100 output/page.jpeg
```

And then report the output resolution and whether it is more readable compared to previous output.

**Comment by rahul-gaidhane** [comment]
yes they are readable now.

**Comment by rahul-gaidhane** [comment]
I should have worked more with each options and combination of options.

**Comment by satyanash** [comment]
Please read up on why these work and the ones you tried did not. And post your findings here.

**Comment by rahul-gaidhane** [comment]
trim option is used to decrease the image file size as it removes the coloured edges of the image.when file size is less images load faster.
quality option helps to prevent the image from an compression when set to 100.
density increases the number of pixels in an image i.e. resolution of image increases.thus the image can be seen clearly.

**Comment by rahul-gaidhane** [comment]
does the quality of thumbnails needs to be improved

**Comment by satyanash** [comment]
For now, no.

**Comment by satyanash** [comment]
Update this thread once this is fixed and pushed.

**Comment by rahul-gaidhane** [comment]
it is fixed now.
but I have question
when we increase the dpi of a given image the size of image should get smaller.In our case the size of image is increasing.why??

**Comment by satyanash** [comment]
> when we increase the dpi of a given image the size of image should get smaller.In our case the size of image is increasing.why?

https://graphicdesign.stackexchange.com/questions/6080/what-is-the-difference-between-dpi-dots-per-inch-and-ppi-pixels-per-inch

Check this out for more confusion :stuck_out_tongue:

**Comment by satyanash** [comment]
> when we increase the dpi of a given image the size of image should get smaller

What is your rationale behind this assertion?
