### ISSUE TITLE
specify input directory as a command line argument

### ISSUE THREAD

**Issue by satyanash** [rahul-gaidhane/project_mag#11]
Currently the input directory is hard coded to `TIFF_FILES`. There is no way to get the program to read the input images from a different directory than that. We should be able to specify the input directory on the command line instead of the program assuming it is always a directory called `TIFF_FILES` in the current working directory.

If no input directory is specified on the command line, the program should quit with a helpful message.

**Comment by rahul-gaidhane** [comment]
fixed
