### ISSUE TITLE
specify output directory as a command line argument 

### ISSUE THREAD

**Issue by satyanash** [rahul-gaidhane/project_mag#12]
Currently the output directory is hard coded to `HTML_FILES`. There is no way to get the program to generate the output into a different directory than that. We should be able to specify the output directory as a command line option.

The program should place all generated HTML and images etc inside this output directory.

If no output directory is specified on the command line, the program should assume a reasonable default.

**Comment by rahul-gaidhane** [comment]
fixed

**Comment by satyanash** [comment]
It looks like the sensible default I mentioned above has been chosen to be the current directory as given by `pwd`. In my opinion it is a bad idea to clobber the current directory's content with your program output.

* If the output directory is not specified, let's instead create a directory called `output` in the current directory and put all our data inside it.
* Since this default directory of `output` will always be generated, we should create a `.gitignore` file and add this directory to it so that git does not keep reminding us that `output` is untracked.

**Comment by rahul-gaidhane** [comment]
fixed

**Comment by satyanash** [comment]
I don't see it. Please ensure that you push your code before commenting that it is fixed.

**Comment by rahul-gaidhane** [comment]
I didn't pushed the code.I pushed it now.

**Comment by satyanash** [comment]
`mkdir` warns if `OUTPUT` already exists.

**Comment by satyanash** [comment]
This problem was already fixed in a previous issue: 
```
mkdir: cannot create directory ‘OUTPUT’: File exists
```

**Comment by rahul-gaidhane** [comment]
fixed
