### ISSUE TITLE
stop tracking the HTML_FILES directory in git

### ISSUE THREAD

**Issue by satyanash** [rahul-gaidhane/project_mag#15]
Since this directory can now be trivially generated by running the script. It may also possibly have an entirely different path as a result of command line arguments. It therefore should no longer be tracked in the version control system.

**Comment by rahul-gaidhane** [comment]
fixed.

**Comment by satyanash** [comment]
I can still see that `HTML_FILES` is still a part of the source code. We need to remove it entirely.

**Comment by rahul-gaidhane** [comment]
I thought they just need to be untracked.so i just put them on .gitignore file. I remove it now.

**Comment by satyanash** [comment]
Hmm. I wasn't clear enough in the first message. But I don't see the committed `.gitignore` either.

**Comment by rahul-gaidhane** [comment]
I added ".gitignore" to .gitignore file.I thought it is of no use to commit the file and send to repository.I am fixing it now

**Comment by satyanash** [comment]
In most cases you want to commit the `.gitignore` file because of this exact case where your code generates some output in the current directory which shouldn't be committed. Since this is a common need for anybody who will use your code, it is useful to commit the `.gitignore` file itself.

**Comment by rahul-gaidhane** [comment]
got it.I forgot repository is in public domain.

**Comment by rahul-gaidhane** [comment]
HTML_FILES directory removed from repository
