### ISSUE TITLE
Move codebase to python

### ISSUE THREAD

**Issue by satyanash** [rahul-gaidhane/project_mag#17]
We need to convert the script from bash to python. This will make it easier to write maintainable code.
We choose python because it is quite easy to get started with.

Create a new `.py` file which will replicate functionality of your shell script but is written in Python.

**Comment by satyanash** [comment]
Make sure you use Python 3.x (not Python 2.x).

**Comment by rahul-gaidhane** [comment]
Can you suggest any good python tutorial ? I did a tutorial but I didn't learn enough to write code for the project.

**Comment by satyanash** [comment]
You can still outsource the image conversion process to the `convert` command, the rest of the features can be done in python itself.

**Comment by satyanash** [comment]
You just need to figure out how to call other commands from within Python

**Comment by satyanash** [comment]
Update on this?

**Comment by rahul-gaidhane** [comment]
I have not started working on it yet.I am working on getting technical know how of the language.Friday onwards python code for project will be developed.I think by monday code will be ready.

**Comment by satyanash** [comment]
We don't need to target all features in Python from the beginning. For the initial version we can just generate the basic tags as we did for the first version of the shell script.

**Comment by rahul-gaidhane** [comment]
yes I will start with basic version of our shell script

**Comment by satyanash** [comment]
Please update on this. We will defer additional features until we have written it in Python.

**Comment by rahul-gaidhane** [comment]
Right now we have reached the point where we can generate single html file per image.It is a function which takes arguments such as PAGE NUMBER, ISSUE MONTH and ISSUE YEAR.Lot of other functionalities yet to be added.I have uploaded them too.

**Comment by rahul-gaidhane** [comment]
I think the python code should have its own much more efficient algorithm to handle our purpose. If we try to make the python code the same way, we made using Linux script is not a good idea. I think there is need to make a good algorithm.We will use features provided by python to develop the further code. Please can you give me some feedback regarding the HTML pages developed and CSS used.Also can you suggest anything about new algorithm ?

**Comment by rahul-gaidhane** [comment]
Got it. Python libraries is the answer. They are of great help for our project.

**Comment by rahul-gaidhane** [comment]
Now I have added the code to generate images from .tif file.Currently, I am stuck with problem to extract images from pdf file.

**Comment by rahul-gaidhane** [comment]
updated code now generates the entire project, when input directory and output directory is passed to main() function.code for some functions is being developed.

**Comment by rahul-gaidhane** [comment]
Now the entire uploaded project is generated by python code.There are few things that needs to be discussed.
