### ISSUE TITLE
add bootstrap CSS and display thumbnail images in a grid

### ISSUE THREAD

**Issue by satyanash** [rahul-gaidhane/project_mag#18]
Add the Bootstrap CSS from the CDN to the HTML files.
Then show all thumbnails in a grid format, instead of in a plain list.

**Comment by satyanash** [comment]
Ensure that you use Bootstrap 4.x (not 3.x/2.x)

**Comment by rahul-gaidhane** [comment]
I 'm learning about bootstrap 4 from w3schools.com.

**Comment by satyanash** [comment]
Well, may I know the progress on the output?

**Comment by satyanash** [comment]
Don't let #17 prevent you from adding features to the current shell script. We can't wait for that to complete.

**Comment by rahul-gaidhane** [comment]
thumbnail images  are displayed using grid .They are also uploaded on server.

**Comment by satyanash** [comment]
Hi, the currently visible output does not look like a grid at all.
What we want is a table-like structure such that we can see the thumbnails arranged in rows and columns.
Right now we have to scroll a lot just to see the available pages as only one thumbnail is visible per row.
Think of how you see the whole list of icons in a given folder when browsing a file manager. Do you see just one icon per row?

Here are a few sample images to give you an idea of what we're trying to achieve:

![https://i.imgur.com/aFc1Trq.png](https://i.imgur.com/aFc1Trq.png)

**Comment by rahul-gaidhane** [comment]
ok .. got it

**Comment by satyanash** [comment]
Note that we **don't** want to use HTML `<table>`. This will just _look_ like a table.
I also noticed that the current implementation uses 3.x.
We need to use Bootstrap 4.x as I mentioned.

**Comment by rahul-gaidhane** [comment]
I was also thinking to make "back to main" button instead of just hypertext.

**Comment by rahul-gaidhane** [comment]
yeah now i made it to bootstrap4.0

**Comment by rahul-gaidhane** [comment]
new grid is made using bootstrap 4.0.
