### ISSUE TITLE
Upload latest output to server

### ISSUE THREAD

**Issue by satyanash** [rahul-gaidhane/project_mag#19]
I have created a new subdomain called at http://sudharak.vistasoftwares.com.

We will upload the contents of your output directory to this server through an FTP client like FileZilla.
We will use this for demo purposes and you should upload your latest generated HTML output to this directory.

I will provide the access credentials on private chat.

**Comment by satyanash** [comment]
Let me know when the latest output has been uploaded and visible at http://sudharak.vistasoftwares.com

**Comment by rahul-gaidhane** [comment]
the entire directory structure of 1990-91 files is uploaded.

**Comment by satyanash** [comment]
Great. But we also want the other ones. Your script needs to figure out a way to read both PDF and TIFF files and combine them into one single output.

**Comment by satyanash** [comment]
Let me know once all the data is uploaded, this includes:

* `1990-91`
* `1991-92`
* `1992-93`
* `1998-99`

**Comment by rahul-gaidhane** [comment]
As soon as possible it will be uploaded.

**Comment by rahul-gaidhane** [comment]
latest files are uploaded on server.

**Comment by satyanash** [comment]
Great, from this point onwards, when a specific feature is uploaded, comment in that respective feature's issue. I am closing this issue now.
