### ISSUE TITLE
Upload data for all months

### ISSUE THREAD

**Issue by satyanash** [rahul-gaidhane/project_mag#21]
Currently, only data for 1990-91 is uploaded, the remaining files need to be generated and uploaded too. Update once data for all the years mentioned below is uploaded.

* `1990-91`
* `1991-92`
* `1992-93`
* `1998-99`

**Comment by rahul-gaidhane** [comment]
yes.

**Comment by rahul-gaidhane** [comment]
well the data for 1991-92, 1992-93, 1998-1999 is also uploaded on server.but we will require an ultimate index page which will provide a link to index page of all the issues.

**Comment by satyanash** [comment]
Yes, so the index page should also be generated by the script.
