### ISSUE TITLE
Add appropriate headings on all pages

### ISSUE THREAD

**Issue by satyanash** [rahul-gaidhane/project_mag#22]
All pages currently directly begin with the content without any headings. We need to add appropriate headings on all pages. The heading can be the same as the page's title for now.

**Comment by rahul-gaidhane** [comment]
I wanted to ask whether there should be some color scheme ?

**Comment by satyanash** [comment]
For now, let's follow the default styling that comes with Bootstrap 4

**Comment by rahul-gaidhane** [comment]
Heading for issue pages is added, rest will be also completed soon.

**Comment by rahul-gaidhane** [comment]
heading for all the pages is added.
