### ISSUE TITLE
Fix redundant nested JSON structure

### ISSUE THREAD

**Issue by satyanash** [rahul-gaidhane/project_mag#23]
Currently metadata files are in the json format, a sample:
```
{ "issue":[
	{ "issuemonth":"April" },
	{ "issueyear":"1990" },
	{ "maxpages":26}
	]
}
```

Here, the `issue` key maps to an array containing three _separate_ objects with the keys: `issuemonth`, `issueyear` and `maxpages`. While this can be parsed, it does not semantically represent an `issue` object.

A more appropriate representation would be a mapping the `issue` key to a **single object** with the three keys (`issuemonth`, `issueyear` and `maxpages`).

If you need to understand how JSON is structured, go through this page: https://json.org/

**Comment by satyanash** [comment]
Once you change your structure, you will also have to change any code that expects an array to the new structure.

**Comment by rahul-gaidhane** [comment]
fixed it.

**Comment by rahul-gaidhane** [comment]
modified meta files are uploaded.
