### ISSUE TITLE
update .gitignore to hide __pycache__ files

### ISSUE THREAD

**Issue by satyanash** [rahul-gaidhane/project_mag#24]
Our `.gitignore` should ignore any `__pycache__` directories that may be created during Python execution.

**Comment by satyanash** [comment]
We should also remove any committed __pycach__ directories from version control.

**Comment by rahul-gaidhane** [comment]
.gitignore updated to ignore _pycache_ dir.

**Comment by satyanash** [comment]
You've added `_pycache_` to `.gitignore`. We need to remove `__pycache__`.

**Comment by rahul-gaidhane** [comment]
so we do not track  _pycache_ directory and also removed the earlier comitted _pycache_.
