### ISSUE TITLE
add appropriate <title> tag to all the generated HTML files

### ISSUE THREAD

**Issue by satyanash** [rahul-gaidhane/project_mag#3]
Every generated HTML file should have an appropriate <title> tag.

**Comment by rahul-gaidhane** [comment]
title tag is added but kept empty. i can modify it to display issuename, and page no.

**Comment by satyanash** [comment]
Yes, please modify it. An empty `<title>` tag is as good as no tag.

**Comment by rahul-gaidhane** [comment]
it is fixed.thinking for some better title tag content.

**Comment by satyanash** [comment]
change it to atleast show the page number for now.

**Comment by satyanash** [comment]
This will benefit from the data available as a result of #9

**Comment by rahul-gaidhane** [comment]
fixed
