### ISSUE TITLE
generate thumbnails for all pages in an issue

### ISSUE THREAD

**Issue by satyanash** [rahul-gaidhane/project_mag#4]
It's very hard to decide which page you want to go to within an issue if you don't know what it looks like.
Use the `convert` command to _also_ generate small thumbnails for every page in the issue and show them on the list of pages HTML instead of just simple links.

**Comment by rahul-gaidhane** [comment]
thumbnail are generated

**Comment by rahul-gaidhane** [comment]
thumbnail are generated

**Comment by satyanash** [comment]
I saw the updated code, the thumbnails are resized in the browser using CSS. We're wasting precious bandwidth by downloading the full sized image and then resizing it on the client. There's also no point to storing a full sized copy of the image as a thumbnail if it is basically the same image.

Also is there any specific reason why you have used the gif format for the thumbnails? JPEG would work just fine.

You have also used the same width and height when resizing the images down to the thumbnails. This messes up the aspect ratio and visually thins/fattens the image based on original dimensions.

Things to fix:
* resize once while generating the thumbnails, instead of resizing everytime in the browser CSS
* switch to using the `jpeg` format for thumbnails
* ensure that the aspect ratio of the image is preserved in the thumbnail
* use a better directory name instead of `GIF_FILES` to store the thumbnails.

**Comment by rahul-gaidhane** [comment]
1.switched to jpeg format for thumbnails.
2.though image size is hardcoded for thumbnails while converting.
3.aspect ratio is maintained for most of the images.
4.directory named switched to **THUMB_FILES** to store the thumbnails.

**Comment by satyanash** [comment]
Aspect ratio is not maintained. You are specifying both a width and a height (250x280). This will distort the image if it is not in that exact ratio. To preserve aspect ratio, we want to only scale by either the width _or_ height.

The hardcoded value works as you yourself have mentioned that it works for _most_ of the current images. This is fine for now but we don't know what all different dimensions we will be getting as input.

**Comment by rahul-gaidhane** [comment]
exactly as I extracted one of pdf file I saw some some images had very different dimensions.My hard coded dimensions won't work for those images.I need to generate files maintaining the aspect ratio for the image

**Comment by satyanash** [comment]
Yes, please scale by either width or the height. Not both.

**Comment by rahul-gaidhane** [comment]
now aspect ratio problem is solved.now problem is images from pdf files are blurred even though I tried to "-quality 100" option while converting the images from pdf files to jpeg files.

**Comment by satyanash** [comment]
That is a separate issue. Please don't mix info from other issues unless they're actually related.

**Comment by satyanash** [comment]
I can see that you've resized at 300px. Should be good enough for now.
