### ISSUE TITLE
re-running script gives warnings

### ISSUE THREAD

**Issue by satyanash** [rahul-gaidhane/project_mag#6]
every subsequent run of the script warns the following two errors for every input file. 
```
mkdir: cannot create directory ‘JPEG_FILES/**April1990**’: File exists
mkdir: cannot create directory ‘HTML_FILES/**April1990**’: File exists
```

**Comment by satyanash** [comment]
This means you're trying to recreate the directory everytime the script runs.
Have a look at the `-p` option of the `mkdir` command.

**Comment by rahul-gaidhane** [comment]
it is fixed now
