### ISSUE TITLE
pages are not naturally ordered

### ISSUE THREAD

**Issue by satyanash** [rahul-gaidhane/project_mag#8]
On the issue page that lists all the pages in a given issue, the pages and thumbnails are not ordered in the way they appear in the scans.

This is probably due to alphabetical sorting. Look into natural sort order which is what is desired here.

**Comment by rahul-gaidhane** [comment]
pages are sorted now. i think issue list on main page should also be sorted as per year and month.

**Comment by rahul-gaidhane** [comment]
issues on main page can sorted as per year and month but looking for better way to do it.

**Comment by satyanash** [comment]
Current code does not work as expected. It uses the last change time (`ctime`) to sort. This is not reliable. We need to go by page number. The page number is a part of the name.

The pages could've been changed in any random order and therefore the `-c` option for `ls` is not reliable for this use case. It _happens_ to work for you because the input files are generated by your scripts serially and therefore have an ascending last modified time.

**Comment by satyanash** [comment]
To better understand the problem, try using the `touch` command to update the `ctime` for any image inside the `JPEG_FILES` directory.  Running `ls -cr` should then show it at the top instead of the one that was there before running `touch`.

**Comment by satyanash** [comment]
Update on this.

**Comment by rahul-gaidhane** [comment]
it is fixed.
but there is a problem with apr1990.tif file.In that file page 4 is on third position and page 3 is on fourth position.It occurs for apr1990 issue.It happens by default.

**Comment by satyanash** [comment]
How did you fix this? What solution did you use?

**Comment by satyanash** [comment]
> but there is a problem with apr1990.tif file.In that file page 4 is on third position and page 3 is on fourth position.It occurs for apr1990 issue.It happens by default.

We can ignore issues with the provided scans. Proper scanning and data fixing can be done later.

**Comment by rahul-gaidhane** [comment]
I just count the number of files in the appropriate directory of an issue containing extracted images. Then add that much links to issue page with proper name.

**Comment by satyanash** [comment]
Hmm.

**Comment by satyanash** [comment]
> I am little concerned about the code for this issue. As i told you how the problem was fixed by counting the number of files in an issue directory.Was this the best way to solve the issue ?  

Given the current constraints, it is an okay solution. If however the pages were not consecutively present. For example you only had pages numbered: 1,2,3,4,7,12,14. Then the current method will also fail. If you want the best way to solve this within shell, look at the `-v` option for the `ls` command.

If later on we have cases where page numbers are not consecutive, we will have to move to real natural ordering through `-v` or something similar in another language.

------
PS. you can still comment/discuss issues even if they're closed. Prefer keeping issue specific discussions on the issue itself.
